#! /usr/bin/env python
#This code will plot user-selected isotherm data, and can also plot literature data.
#This code will create a constant temperature isotherm plot. It should be executed in the directory containing all of the loading directories for a specified condition, i.e. temperature.
import readline
import numpy as np
import math
import matplotlib.pyplot as plt
from re import sub
import time
import subprocess

readline.parse_and_bind("tab: complete")
readline.set_completer_delims(readline.get_completer_delims().replace('-',''))

#standard variables
isothermType = np.array(['excess', 'absolute'])
unitArray = np.array(['molecules/unit cell', 'mol/kg framework', 'milligram/gram framework', 'cm^3 (STP)/gr framework', 'cm^3 (STP)/cm^3 framework'])
unitPositionArray = np.array([5,5,5,6,6])
dataSetLabels = np.array([])
colorArray = np.array([])
kolor = np.array(['g','m','b','k','c','r','y'])
markerA = np.array(['o','d','h','s','*','v','p'])
style = np.array(['-','--','-.',':'])

#determine who the user is
user = subprocess.Popen(r'whoami', stdout=subprocess.PIPE)
name = str(user.communicate()[0].split()).replace("['","").replace("']","")
#define tick mark font size
plt.rc('xtick', labelsize=10)
plt.rc('ytick', labelsize=10)
plt.rcParams["figure.figsize"] = 6,4
plt.rcParams["figure.dpi"]= 300
handle = 0
fig,ax = plt.subplots()
while (handle != 1 and handle != 2):
    selector = raw_input('\nDo you want a:\n1: Standard plot\n2: Semi-log plot\n')
    if (selector == '1'):
        handle = 1
    elif (selector == '2'):
        handle = 2
    else:
        print('\nInvalid entry. Try again.\n')
#identify all the isotherms that could be plotted, but first open a dump file for error output
adsorptionType = 0
while (adsorptionType != 1 and adsorptionType != 2):
    selector = raw_input('\nChoose desired adsorption type:\n1: Excess adsorption\n2: Absolute adsorption\n\n')
    if (selector == '1'):
        adsorptionType = 1
    elif (selector == '2'):
        adsorptionType = 2
    else:
        print('\nInvalid entry. Try again.\n')
print('\nPlease wait while I gather all the data. This could take a minute.\n')
if name == 'jpr54':
    f = open('/ihome/kjohnson/jpr54/trash.txt', "w")
user1Path = '/ihome/kjohnson/jpr54/raspa/isotherms'
user1gen = subprocess.Popen('find -name "Isotherm" -printf "%h\n"', stdout=subprocess.PIPE, stderr=f, cwd=user1Path, shell=True)
user1Locs = user1gen.communicate()[0].split()
user1Locs = [k.split('.',1)[1] for k in user1Locs]
user1LocsF = [user1Path+'{0}'.format(b) for b in user1Locs]
f.close()
if name == 'jpr54':
    subprocess.Popen('rm /ihome/kjohnson/jpr54/trash.txt', shell=True)
availableIsotherms = user1LocsF #+ user2LocsF
aControl = 0
print('Available isotherms for plotting:\n')
for j, line in enumerate(availableIsotherms):
    print('{0}: {1}'.format(j + 1,line.split('isotherms',1)[1]))
while aControl == 0:
    print('\nEnter the numbers corresponding to the calculations you would like to plot, separated by spaces.\n')
    calcNumbers = raw_input('For example: 0 1\n')
    calcNumList = np.unique(np.array([int(s) for s in calcNumbers.split() if s.isdigit()]))
    if calcNumList.any():
        aControl = 1
    else:
        print('\nPlease try again.\n')
calcNumList[:] = [x - 1 for x in calcNumList]
styleSelect = -1

#determine desired units
print('\nThe available units are:\n1: molecules/unit cell\n2: mol/kg framework\n3: milligram/gram framework\n4: cm^3 (STP)/gram framework\n5: cm^3 (STP)/cm^3 framework\n')
unitControl = 0
while unitControl == 0:
    unitSelection = raw_input('\nEnter the number corresponding to the desired unit.\n')
    if unitSelection == '1' or unitSelection == '2' or unitSelection == '3' or unitSelection == '4' or unitSelection == '5':
        unitControl = int(unitSelection)
    else:
        print('\nInvalid input. Try again.\n')

#plot the calculated data
for count, p in enumerate(calcNumList):
    Dirs = subprocess.Popen('ls -d */', stdout=subprocess.PIPE, cwd=availableIsotherms[p], shell=True)
    Pressures = Dirs.communicate()[0].replace("mbar/\n"," ").split()
    pressures1 = np.sort(np.array([float(i) for i in Pressures]))
    loading = []
    for pressure in pressures1:
        loc = availableIsotherms[p]+'/'+'{0}mbar/Output/System_0/'.format(str(pressure))
        getData = subprocess.Popen('grep -F "Average loading {0} [{1}" output_*'.format(isothermType[adsorptionType-1],unitArray[unitControl-1]), stdout=subprocess.PIPE, cwd=loc, shell=True)
        loading.append(float(getData.communicate()[0].split()[unitPositionArray[unitControl-1]]))
    loading1 = np.array(loading)
    labelDir = subprocess.Popen('printf "%s" "${PWD##*/}"', stdout=subprocess.PIPE, cwd=availableIsotherms[p], shell=True)
    dataSetLabels = np.append(dataSetLabels,labelDir.communicate()[0])
    styleSelect = styleSelect + 1
    if styleSelect == 4:
        styleSelect = 0
    if (handle == 1):
        colorHolder, = plt.plot(pressures1, loading1, label=dataSetLabels[count].split('_')[0], linewidth=2.0, color=kolor[count], linestyle=style[styleSelect])
    elif (handle == 2):
        colorHolder, = plt.semilogx(pressures1, loading1, label=dataSetLabels[count].split('_')[0], linewidth=2.0, color=kolor[count], linestyle=style[styleSelect])
    filename = dataSetLabels[count]
    #print the raw data sets
    #need to modify to make sure nothing gets overwritten when different units are used
    makeRaw = open("/ihome/kjohnson/jpr54/raspa/isotherms/plotData/{0}".format(filename), 'w')
    makeRaw.write('mbar\t{0}\n'.format(unitArray[unitControl-1]))
    for k in range(0,len(pressures1)):
        makeRaw.write('{0}\t{1}\n'.format(pressures1[k], loading1[k]))
    makeRaw.close()
    colorArray = np.append(colorArray, colorHolder.get_color()) 
#determine if a literature data set needs to be plotted
controller = 0
while (controller != 1):
    inputRequiredController = raw_input('\n\nDo data sets from the literature need to be plotted? (y/n)\n')
    if (inputRequiredController == 'n'):
        controller = 1
    elif (inputRequiredController == 'y'):
        controller = 1
        #now display the data file names in th literatureData directory for the user
        litData = subprocess.Popen(r'ls /ihome/kjohnson/jpr54/raspa/isotherms/literatureData/', stdout=subprocess.PIPE, shell=True)
        litDataLines = litData.communicate()[0].split()
        print('\nData for the following calculations are available:\n')
        for i, line in enumerate(litDataLines):
            print('{0}: {1}'.format(i,line))
        #now determine which data sets the user would like to include
        print('\nEnter the numbers corresponding to the calculations you would like to plot, separated by spaces.\n')
        litNumbers = raw_input('For example: 0 1\n')
        litNumList = np.unique(np.array([int(s) for s in litNumbers.split() if s.isdigit()]))
    else:
        time.sleep(2)
        print('\n\nInvalid entry. Please try again.\n')
        time.sleep(1)
#bring in the desired literature data
markerCount = 0
if inputRequiredController == 'y':
    for dCount, P in enumerate(litNumList):
        tempPressArrayA = np.array([])
        tempLoadingArrayA = np.array([])
        tempPressArrayD = np.array([])
        tempLoadingArrayD = np.array([])
        #dataSetLabels = np.append(dataSetLabels, litDataLines[int(P)])
        fileName = '/ihome/kjohnson/jpr54/raspa/isotherms/literatureData/' + litDataLines[int(P)]
    #read in the data
        tempFile = open(fileName, 'r')
        tempLines = tempFile.readlines()
        tempFile.close()
        tempLine = tempLines[0][:-1]
        #save the first line in the label, plot the literature data
        #match the colors
        testLabel = litDataLines[int(P)].split('_',1)[0] + '_' + litDataLines[int(P)].split('_',2)[1] + '_' + litDataLines[int(P)].split('_',3)[2]
        colorSuccess = 0
        adSelector = 0
        for kCounter, nameString in enumerate(dataSetLabels[:]):
            if (testLabel in nameString):
                colorMatch = colorArray[kCounter]
                colorSuccess = 1
            for jCount, line in enumerate(tempLines):
                #first two lines are the name and the units
                if (jCount > 1):
                    #add the data to the adsorption and desorption arrays
                    if "adsorption" in line:
                        adSelector = 1
                    elif "desorption" in line:
                        adSelector = 2
                    elif adSelector == 1:
                        tempPressArrayA = np.append(tempPressArrayA, line.split()[0])
                        tempLoadingArrayA = np.append(tempLoadingArrayA, line.split()[1])
                    elif adSelector == 2:
                        tempPressArrayD = np.append(tempPressArrayD, line.split()[0])
                        tempLoadingArrayD = np.append(tempLoadingArrayD, line.split()[1])
                    legendSelection = 0
                    # while (legendSelection != 1):
                    #print('What information do you need to include in the legend? Calculation/literature is added automatically.\n')
                    # legendSelection = int(raw_input('1: MOF name only\n2: MOF name and adsorbate\n3:MOF name, adsorbate, and temperature\n4: MOF name and temperature\n5: Adsorbate and temperature\n6: No additional information.'))
                    # plt.plot(tempPressArray, tempLoadingArray, label=dataSetLabels[dCount].rsplit('_',2)[0].replace('_',' ')+' Literature', marker='o', markersize=10, linestyle='none')
            #dataSetLabels = np.append(dataSetLabels, tempLine)
        if markerCount > 6:
            markerCount = 0
        if len(tempLoadingArrayD) != 0:
            experimentString = " Experiment, A"
        else:
            experimentString = " Experiment"
        if (colorSuccess == 1):
            if (handle == 1):
                plt.plot(tempPressArrayA, tempLoadingArrayA, label=tempLine.split('_',1)[0]+experimentString, marker=markerA[markerCount], markersize=4, linestyle='none', color=colorMatch)
                if len(tempLoadingArrayD) != 0:
                    plt.plot(tempPressArrayD, tempLoadingArrayD, label=tempLine.split('_',1)[0]+" Experiment, D", marker=markerA[markerCount], markersize=4, linestyle='none', color=colorMatch, markerfacecolor='w')
                markerCount = markerCount + 1
            elif (handle == 2):
                plt.semilogx(tempPressArrayA, tempLoadingArrayA, label=tempLine.split('_',1)[0]+experimentString, marker=markerA[markerCount], markersize=4, linestyle='none', color=colorMatch)
                if len(tempLoadingArrayD) != 0:
                    plt.semilogx(tempPressArrayD, tempLoadingArrayD, label=tempLine.split('_',1)[0]+" Experiment, D", marker=markerA[markerCount], markersize=4, linestyle='none', color=colorMatch, markerfacecolor='w')
                markerCount = markerCount + 1
        elif (colorSuccess == 0):
            if (handle == 1):
                plt.plot(tempPressArrayA, tempLoadingArrayA, label=tempLine.split('_',1)[0]+experimentString, marker=markerA[markerCount], markersize=4, linestyle='none')
                if len(tempLoadingArrayD) != 0:
                    plt.plot(tempPressArrayD, tempLoadingArrayD, label=tempLine.split('_',1)[0]+" Experiment, D", marker=markerA[markerCount], markersize=4, linestyle='none', markerfacecolor='w')
                markerCount = markerCount + 1
            elif (handle == 2):
                plt.semilogx(tempPressArrayA, tempLoadingArrayA, label=tempLine.split('_',1)[0]+experimentString, marker=markerA[markerCount], markersize=4, linestyle='none')
                if len(tempLoadingArrayD) != 0:
                    plt.semilogx(tempPressArrayD, tempLoadingArrayD, label=tempLine.split('_',1)[0]+" Experiment, D", marker=markerA[markerCount], markersize=4, linestyle='none', markerfacecolor='w')
                markerCount = markerCount + 1
#determine upper axis limits
xMax = int(math.ceil(float(max(pressures1))))
yMax = int(math.ceil(float(max(loading1))))
#get plot title
#pT = subprocess.Popen('pwd', stdout=subprocess.PIPE)
#plotTitle = str(str(pT.communicate()[0].split()[0])).rsplit('/',1)[1]
#finally, we have two numpy arrays that contain the data we need. Make the plot and save it
#plt.plot(pressures1,loading1,label=dataLabel.rsplit('_',3)[0].replace('_',' ')+' Calculated', linewidth=2.0)
#plt.plot(pressures1,loading1,label='Calculated', linewidth=3.0, marker='*', markersize=14)
plt.ylabel('{0} Loading ({1})'.format(isothermType[adsorptionType-1].capitalize(),unitArray[unitControl-1]), fontsize=10)
plt.xlabel('Pressure (mbar)', fontsize=10)
handles, labels = ax.get_legend_handles_labels()
labels, handles = zip(*sorted(zip(labels, handles), key=lambda t: t[0]))
if handle == 1:
    plt.legend(handles, labels, loc=2,prop={'size':7},frameon=False)
elif handle == 2:
    plt.legend(handles, labels, loc=2,prop={'size':10},frameon=False)
plt.subplots_adjust(bottom=0.16)

plt.axis((0.1,10000,0,60))
#uncomment following line when doing normal operation
#plt.axis((0.00001,.5,0,yMax*1.2))

#write the plot to a file if desired
pControl = 0
while pControl != 1:
    savePlot = raw_input('\nDo you want to save the plot? (y/n)\n')
    if (savePlot == 'y'):
        plotTitle = raw_input('\nEnter a name for the plot.\n')
        plt.savefig("/ihome/kjohnson/jpr54/raspa/isotherms/plots/{0}".format(plotTitle), dpi = 600)
        pControl = 1
    elif (savePlot == 'n'):
        pControl = 1
    else:
        print('Try again.\n')
plt.show()
